export const DEFAULT_CONCEPTS = [
  "The Great Wall of China",
  "Photosynthesis",
  "Black Hole",
  "Mona Lisa",
  "World War II",
  "Mount Everest",
  "DNA replication",
  "The Internet",
  "French Revolution",
  "Pythagorean theorem",
  "Electricity",
  "Climate change",
  "Machine learning",
  "Shakespeare",
  "Solar eclipse",
  "Periodic table",
  "Amazon rainforest",
  "The Pacific Ocean",
  "Ancient Egypt",
  "Plate tectonics",
  "Bitcoin",
  "Basketball",
  "The human brain",
  "Vaccines",
  "The Moon landing",
  "Tokyo",
  "Jazz music",
  "Volcano",
  "Gravity",
  "Mars rover",
  "The Renaissance",
  "Opera",
  "Blockchain",
  "Neural network",
  "Penguins",
  "The Statue of Liberty",
  "Cloud computing",
  "Game theory",
  "Roman Empire",
  "Antarctica",
  "Hurricane",
  "Photoshop",
  "Coral reef",
  "Artificial intelligence",
  "The Nile River",
  "Chess",
  "Olympic Games",
  "Saturn rings",
  "Quantum mechanics",
  "Renewable energy",
  "Bee pollination",
  "The Grand Canyon",
  "Internet memes",
  "Caffeine",
  "Solar panels",
  "Opera singer",
  "Fingerprint",
  "Human heart",
  "Submarine",
  "Tsunami"
] as const;

export function pickConcept(used: string[]) {
  const available = DEFAULT_CONCEPTS.filter((c) => !used.includes(c));
  const pool = available.length > 0 ? available : [...DEFAULT_CONCEPTS];
  return pool[Math.floor(Math.random() * pool.length)];
}
